export type FieldType = "text" | "textarea";

export interface SectionField {
  key: string;      // i18n dot-notation key e.g. "hero.badge"
  label: string;    // human-readable
  type: FieldType;
}

export const SECTION_FIELDS: Record<string, SectionField[]> = {
  hero: [
    { key: "hero.badge",        label: "Badge Text",         type: "text" },
    { key: "hero.title1",       label: "Title — Part 1",     type: "text" },
    { key: "hero.title_accent", label: "Title — Accent Word",type: "text" },
    { key: "hero.title2",       label: "Title — Part 2",     type: "text" },
    { key: "hero.subtitle",     label: "Subtitle",           type: "textarea" },
    { key: "hero.cta_primary",  label: "Primary Button",     type: "text" },
    { key: "hero.cta_secondary",label: "Secondary Button",   type: "text" },
    { key: "hero_badges.b1",    label: "Badge 1 (Experience)",type: "text" },
    { key: "hero_badges.b2",    label: "Badge 2 (Clients)",  type: "text" },
    { key: "hero_badges.b3",    label: "Badge 3 (Services)", type: "text" },
  ],
  stats: [
    { key: "stats.s1", label: "Stat 1 Label", type: "text" },
    { key: "stats.s2", label: "Stat 2 Label", type: "text" },
    { key: "stats.s3", label: "Stat 3 Label", type: "text" },
    { key: "stats.s4", label: "Stat 4 Label", type: "text" },
  ],
  problem: [
    { key: "problem.badge",     label: "Badge",          type: "text" },
    { key: "problem.title_1",   label: "Title Part 1",   type: "text" },
    { key: "problem.title_accent", label: "Title Accent",type: "text" },
    { key: "problem.title_2",   label: "Title Part 2",   type: "text" },
    { key: "problem.subtitle",  label: "Subtitle",       type: "textarea" },
    { key: "problem.p1_title",  label: "Problem 1 Title",type: "text" },
    { key: "problem.p1_desc",   label: "Problem 1 Desc", type: "textarea" },
    { key: "problem.p2_title",  label: "Problem 2 Title",type: "text" },
    { key: "problem.p2_desc",   label: "Problem 2 Desc", type: "textarea" },
    { key: "problem.p3_title",  label: "Problem 3 Title",type: "text" },
    { key: "problem.p3_desc",   label: "Problem 3 Desc", type: "textarea" },
  ],
  services: [
    { key: "services.badge",    label: "Badge",          type: "text" },
    { key: "services.title",    label: "Title",          type: "text" },
    { key: "services.subtitle", label: "Subtitle",       type: "textarea" },
  ],
  about: [
    { key: "about.title",        label: "Title",           type: "text" },
    { key: "about.subtitle",     label: "Subtitle",        type: "text" },
    { key: "about.exp_label",    label: "Experience Label",type: "text" },
    { key: "about.desc1",        label: "Description 1",   type: "textarea" },
    { key: "about.desc2",        label: "Description 2",   type: "textarea" },
    { key: "about.mission",      label: "Mission Title",   type: "text" },
    { key: "about.mission_desc", label: "Mission Text",    type: "textarea" },
    { key: "about.vision",       label: "Vision Title",    type: "text" },
    { key: "about.vision_desc",  label: "Vision Text",     type: "textarea" },
  ],
  academy: [
    { key: "academy.title",        label: "Title",         type: "text" },
    { key: "academy.subtitle",     label: "Subtitle",      type: "text" },
    { key: "academy.desc",         label: "Description",   type: "textarea" },
    { key: "academy.cta",          label: "View All CTA",  type: "text" },
    { key: "academy.register_cta", label: "Enroll CTA",    type: "text" },
  ],
  odoo: [
    { key: "odoo.badge",     label: "Badge",        type: "text" },
    { key: "odoo.title_1",   label: "Title Part 1", type: "text" },
    { key: "odoo.title_accent", label: "Title Accent", type: "text" },
    { key: "odoo.subtitle",  label: "Subtitle",     type: "textarea" },
    { key: "odoo.m1_title",  label: "Module 1 Title",type: "text" },
    { key: "odoo.m1_desc",   label: "Module 1 Desc", type: "textarea" },
    { key: "odoo.m2_title",  label: "Module 2 Title",type: "text" },
    { key: "odoo.m2_desc",   label: "Module 2 Desc", type: "textarea" },
    { key: "odoo.m3_title",  label: "Module 3 Title",type: "text" },
    { key: "odoo.m3_desc",   label: "Module 3 Desc", type: "textarea" },
    { key: "odoo.m4_title",  label: "Module 4 Title",type: "text" },
    { key: "odoo.m4_desc",   label: "Module 4 Desc", type: "textarea" },
    { key: "odoo.m5_title",  label: "Module 5 Title",type: "text" },
    { key: "odoo.m5_desc",   label: "Module 5 Desc", type: "textarea" },
    { key: "odoo.m6_title",  label: "Module 6 Title",type: "text" },
    { key: "odoo.m6_desc",   label: "Module 6 Desc", type: "textarea" },
  ],
  whyus: [
    { key: "why.badge",    label: "Badge",       type: "text" },
    { key: "why.title",    label: "Title",       type: "text" },
    { key: "why.subtitle", label: "Subtitle",    type: "textarea" },
    { key: "why.p1_title", label: "Point 1 Title",type: "text" },
    { key: "why.p1_desc",  label: "Point 1 Desc", type: "textarea" },
    { key: "why.p2_title", label: "Point 2 Title",type: "text" },
    { key: "why.p2_desc",  label: "Point 2 Desc", type: "textarea" },
    { key: "why.p3_title", label: "Point 3 Title",type: "text" },
    { key: "why.p3_desc",  label: "Point 3 Desc", type: "textarea" },
    { key: "why.p4_title", label: "Point 4 Title",type: "text" },
    { key: "why.p4_desc",  label: "Point 4 Desc", type: "textarea" },
  ],
  testimonials: [
    { key: "testimonials.badge",   label: "Badge",    type: "text" },
    { key: "testimonials.title",   label: "Title",    type: "text" },
    { key: "testimonials.subtitle",label: "Subtitle", type: "text" },
    { key: "testimonials.t1_text", label: "Review 1", type: "textarea" },
    { key: "testimonials.t1_name", label: "Name 1",   type: "text" },
    { key: "testimonials.t1_role", label: "Role 1",   type: "text" },
    { key: "testimonials.t2_text", label: "Review 2", type: "textarea" },
    { key: "testimonials.t2_name", label: "Name 2",   type: "text" },
    { key: "testimonials.t2_role", label: "Role 2",   type: "text" },
    { key: "testimonials.t3_text", label: "Review 3", type: "textarea" },
    { key: "testimonials.t3_name", label: "Name 3",   type: "text" },
    { key: "testimonials.t3_role", label: "Role 3",   type: "text" },
  ],
  blog: [
    { key: "blog.badge",   label: "Badge",    type: "text" },
    { key: "blog.title",   label: "Title",    type: "text" },
    { key: "blog.subtitle",label: "Subtitle", type: "textarea" },
  ],
  cta: [
    { key: "cta.title",      label: "Headline",      type: "textarea" },
    { key: "cta.subtitle",   label: "Subtitle",      type: "textarea" },
    { key: "cta.btn_enroll", label: "Button 1",      type: "text" },
    { key: "cta.pill1",      label: "Pill 1",        type: "text" },
    { key: "cta.pill2",      label: "Pill 2",        type: "text" },
    { key: "cta.pill3",      label: "Pill 3",        type: "text" },
  ],
  contact: [
    { key: "contact.badge",   label: "Badge",    type: "text" },
    { key: "contact.title",   label: "Title",    type: "text" },
    { key: "contact.subtitle",label: "Subtitle", type: "text" },
  ],
  register: [
    { key: "register.title",   label: "Title",    type: "text" },
    { key: "register.subtitle",label: "Subtitle", type: "text" },
    { key: "register.submit",  label: "Submit Button", type: "text" },
  ],
  faq: [
    { key: "faq.badge",   label: "Badge",   type: "text" },
    { key: "faq.title",   label: "Title",   type: "text" },
    { key: "faq.subtitle",label: "Subtitle",type: "text" },
  ],
};
